---
local_route: 10.36.166.28
port: 8181
pid_filename: /home/work/cloud_controller_ng/status/cloud_controller_ng.pid
message_bus_uri: nats://n_user:n_passwd@10.36.166.28:8444/

external_domain: [api2.vcap.me]

bootstrap_admin_email: jpaas@baidu.com

system_domain_organization: the-system_domain-org-name
system_domain: vcap.me
app_domains:
  - vcap.me

info:
  name: "vcap"
  build: "2222"
  version: 2
  support_address: "http://jpaas.baidu.com"
  description: "JPaas"
  api_version: "2.0.0"
# TODO: put back once json schema is sorted out
# allow_debug: false

nginx:
  use_nginx: false
  instance_socket: "/var/vcap/sys/run/cloud_controller_ng/cloud_controller.sock"

logging:
  file: /home/work/cloud_controller_ng/log/cloud_controller.log
  level: debug2

db:
  database: mysql2://work_cc:work_cc@10.36.166.28:8584/cc_ng
  max_connections: 32
  pool_timeout: 10

uaa:
  url: http://10.36.166.28:8080/uaa
  resource_id: "cloud_controller"
  symmetric_secret: tokensecret

cc_partition: yeti

bulk_api:
  auth_user: bulk_user
  auth_password: bulk_password

# App staging parameters
staging:
  # Max duration for staging process
  max_staging_runtime: 10000 # secs
  auth:
    user: zxsfhgjg
    password: ZNVfdase9

quota_definitions:
  free:
    non_basic_services_allowed: false
    total_services: 2
    memory_limit: 204800000 # 200000 GB
  paid:
    non_basic_services_allowed: true
    total_services: 500
    memory_limit: 204800000 # 200000 GB
  trial:
    non_basic_services_allowed: false
    total_services: 2
    memory_limit: 204800000 # 200000 GB
    trial_db_allowed: true

default_quota_definition: free

resource_pool:
  resource_directory_key: cc-resources
  fog_connection:
    provider: Local
    local_root: /home/work/cc_resource

packages:
  resource_directory_key: cc-packages
  fog_connection:
    provider: Local
    local_root: /home/work/cc_resource

droplets:
  droplet_directory_key: cc-droplets
  unzipdroplet_directory_key: cc-unzipdroplets
  seed_dir: ginko3_seed
  use_p2p: true
  fog_connection:
    provider: Local
    local_root: /home/work/cc_resource

db_encryption_key: "asdfasdfasdf"

trial_db:
  guid: "78ad16cf-3c22-4427-a982-b9d35d746914"

exclusive_deploy: false
